pipeline{
    environment {
    imagename = "bookingengine-fe"
    dockerImage = ''
  }
    agent any
    stages {
        stage('CheckOut'){
            steps {
                git branch: 'main', url: 'https://github.com/MS396584/BookingEngine.git'
            }
        }
       stage('Build'){
           steps{
                sh 'docker build -t bookingengine-client -f client/Dockerfile .'
                }
           }
       stage('Sonar Analysis'){
            steps {
                 withSonarQubeEnv("scan") {
                 sh "${tool("scan")}/bin/sonar-scanner -Dsonar.projectKey=Bookingfe -Dsonar.projectName=BookingEngine-fe -Dsonar.sources=client"
                
                                       }
                 }
           }
        stage('nexus'){
            steps{
                sh 'docker tag bookingengine-client localhost:8095/booking/bookingengine-client:2.0'
                sh 'docker login -u admin -p admin123 localhost:8095'
                sh 'docker push localhost:8095/booking/bookingengine-client:2.0'
            }
        }
      stage('run the container'){
            steps{
                sh 'docker pull localhost:8095/booking/bookingengine-client:2.0'
               
                sh 'docker run --name booking-client -p 3000:3000 localhost:8095/booking/bookingengine-client:2.0'
            }
        }
    }
}
